const C=document.getElementById('canvas'),X=C.getContext('2d');
const $=id=>document.getElementById(id);let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2);
function resize(){W=innerWidth;H=innerHeight;C.width=W*DPR;C.height=H*DPR;X.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const imgCache={};function img(src){if(!imgCache[src]){const i=new Image;i.src=src;imgCache[src]=i}return imgCache[src]}
const atlases={towers:{i:img('assets/generated/towers_atlas.webp'),cols:4,rows:5},enemies:{i:img('assets/generated/enemies_early_atlas.webp'),cols:3,rows:8},late_enemies:{i:img('assets/generated/enemies_late_atlas.webp'),cols:3,rows:8},cupcake:{i:img('assets/generated/cupcake_atlas.webp'),cols:4,rows:2}};
const bg=img('assets/generated/battlefield.jpg');
let state;
const upgrades={damage:{name:'POTENCIA',icon:'💥',desc:'+30% daño',apply:s=>s.damage*=1.3},speed:{name:'CADENCIA',icon:'⚙️',desc:'20% más rápido',apply:s=>s.fireDelay=Math.max(80,s.fireDelay*.8)},multi:{name:'MULTIDISPARO',icon:'🏹',desc:'+1 proyectil',apply:s=>s.multishot++},bounce:{name:'REBOTE',icon:'↩️',desc:'+1 rebote',apply:s=>s.bounces++},explode:{name:'EXPLOSIÓN',icon:'💣',desc:'impactos explotan',apply:s=>s.explosion+=18},crit:{name:'CRÍTICO',icon:'🎯',desc:'+12% crítico',apply:s=>s.crit=Math.min(.75,s.crit+.12)},fire:{name:'FUEGO',icon:'🔥',desc:'daño continuo',apply:s=>s.fire+=3},ice:{name:'HIELO',icon:'❄️',desc:'ralentiza',apply:s=>s.ice=Math.min(.7,s.ice+.12)},lightning:{name:'RAYO',icon:'⚡',desc:'salta a otro enemigo',apply:s=>s.lightning++},pierce:{name:'PERFORAR',icon:'🗡️',desc:'+1 perforación',apply:s=>s.pierce++}};
const upgradeKeys=Object.keys(upgrades);
function reset(){state={running:true,time:0,wave:1,waveTime:0,waveDuration:46,spawnClock:0,enemies:[],shots:[],fx:[],hp:100,gold:0,bonus:0,towerLevel:1,damage:22,fireDelay:620,lastShot:0,multishot:1,bounces:0,explosion:0,crit:.05,fire:0,ice:0,lightning:0,pierce:0,levels:{},paused:false,bossSpawned:false,powerAt:8+Math.random()*18,powerLive:false,powerUntil:0};sync()}
function sync(){$('hp').textContent=Math.max(0,Math.ceil(state.hp));$('wave').textContent=state.wave;$('gold').textContent=state.gold;$('bonus').textContent=state.bonus;$('towerLevel').textContent=state.towerLevel}
function enemyDef(w){if(w<7)return{set:'enemies',row:0,hp:35,spd:34,size:62};if(w<14)return{set:'enemies',row:1,hp:70,spd:30,size:75};if(w<21)return{set:'enemies',row:2,hp:95,spd:36,size:78};if(w<28)return{set:'enemies',row:3,hp:125,spd:31,size:70};if(w<34)return{set:'enemies',row:4,hp:190,spd:24,size:82};if(w<40)return{set:'enemies',row:5,hp:260,spd:27,size:90};if(w<46)return{set:'enemies',row:6,hp:330,spd:25,size:82};if(w<51)return{set:'enemies',row:7,hp:430,spd:22,size:82};if(w<56)return{set:'late_enemies',row:3,hp:650,spd:21,size:105};if(w<60)return{set:'late_enemies',row:6,hp:900,spd:19,size:120};return{set:'late_enemies',row:7,hp:12500,spd:10,size:Math.min(H*.72,560),boss:true}}
function spawn(){let d=enemyDef(state.wave);if(state.wave===60&&state.bossSpawned)return;if(d.boss)state.bossSpawned=true;let y=d.boss?H*.76:H*(.46+Math.random()*.32);state.enemies.push({x:W+d.size*.6,y,hp:d.hp*(1+state.wave*.035),max:d.hp*(1+state.wave*.035),spd:d.spd*(1+state.wave*.004),size:d.size,set:d.set,row:d.row,frame:0,anim:0,boss:d.boss,burn:0,slow:0,attack:0})}
function shoot(t){if(!t)return;for(let i=0;i<state.multishot;i++){let spread=(i-(state.multishot-1)/2)*18;state.shots.push({x:W*.19,y:H*.49+spread,target:t,damage:state.damage,pierce:state.pierce,bounce:state.bounces,dead:false})}}
function hit(e,s){let dmg=s.damage*(Math.random()<state.crit?2:1);e.hp-=dmg;e.burn=Math.max(e.burn,state.fire*4);e.slow=Math.max(e.slow,state.ice);state.fx.push({x:e.x,y:e.y,t:.18,type:0});if(state.explosion){for(const o of state.enemies){if(o!==e&&Math.hypot(o.x-e.x,o.y-e.y)<95)o.hp-=state.explosion}}if(state.lightning){for(const o of state.enemies.filter(o=>o!==e&&o.hp>0).sort((a,b)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(b.x-e.x,b.y-e.y)).slice(0,state.lightning)){o.hp-=dmg*.35;state.fx.push({x:o.x,y:o.y,t:.16,type:1})}}}
function chooseCards(){state.paused=true;$('cards').classList.remove('hidden');$('cardWrap').innerHTML='';for(const k of [...upgradeKeys].sort(()=>Math.random()-.5).slice(0,3)){let u=upgrades[k],lv=(state.levels[k]||0)+1,d=document.createElement('div');d.className='card';d.innerHTML=`<div class=icon>${u.icon}</div><h3>${u.name}</h3><div class=lvl>NIVEL ${lv}</div><p>${u.desc}</p>`;d.onclick=()=>{state.levels[k]=lv;u.apply(state);state.towerLevel=Math.min(20,state.towerLevel+1);$('cards').classList.add('hidden');state.paused=false;state.wave++;state.waveTime=0;state.spawnClock=0;state.bossSpawned=false;state.powerAt=8+Math.random()*18;state.powerLive=false;sync()};$('cardWrap').appendChild(d)}}
function grantExtraDraft(){if(!state.running||state.paused)return;state.bonus++;sync();setTimeout(()=>{if(state.running&&!state.paused&&state.bonus>0){state.bonus--;chooseCards();sync()}},250)}
$('powerup').onclick=()=>{if(!state.powerLive)return;state.powerLive=false;$('powerup').classList.add('hidden');grantExtraDraft()};
function end(win){state.running=false;$('endTitle').textContent=win?'¡EL CUPCAKE SOBREVIVIÓ!':'EL CUPCAKE CAYÓ';$('endText').textContent=win?'La torre terminó convertida en una monstruosidad gloriosa.':'La próxima build será todavía más absurda.';$('end').classList.remove('hidden')}
function update(dt){if(!state.running||state.paused)return;state.time+=dt;state.waveTime+=dt;state.spawnClock+=dt;if(state.wave<60||!state.bossSpawned){let interval=Math.max(.95,2.6-state.wave*.025);if(state.spawnClock>interval){state.spawnClock=0;spawn()}}if(state.waveTime>state.powerAt&&!state.powerLive&&state.powerAt<90){state.powerLive=true;state.powerUntil=state.time+1.6;state.powerAt=999;$('powerup').style.left=(45+Math.random()*35)+'%';$('powerup').style.top=(34+Math.random()*42)+'%';$('powerup').classList.remove('hidden')}if(state.powerLive&&state.time>state.powerUntil){state.powerLive=false;$('powerup').classList.add('hidden')}if(state.time-state.lastShot>state.fireDelay/1000){state.lastShot=state.time;shoot(state.enemies.filter(e=>e.hp>0).sort((a,b)=>a.x-b.x)[0])}for(const e of state.enemies){e.anim+=dt;if(e.anim>.22){e.anim=0;e.frame=1-e.frame}if(e.burn>0){e.hp-=state.fire*dt;e.burn-=dt}e.x-=e.spd*(1-(e.slow||0))*dt;if(e.x<W*.14){state.hp-=e.boss?20:Math.max(2,e.max/180);e.hp=0;sync();if(state.hp<=0)return end(false)}}for(const s of state.shots){if(s.dead)continue;let t=s.target;if(!t||t.hp<=0){t=state.enemies.filter(e=>e.hp>0).sort((a,b)=>Math.hypot(a.x-s.x,a.y-s.y)-Math.hypot(b.x-s.x,b.y-s.y))[0];s.target=t;if(!t){s.dead=true;continue}}let dx=t.x-s.x,dy=t.y-s.y,L=Math.hypot(dx,dy)||1;s.x+=dx/L*620*dt;s.y+=dy/L*620*dt;if(L<t.size*.38+12){hit(t,s);if(s.pierce>0)s.pierce--;else if(s.bounce>0){s.bounce--;s.target=state.enemies.filter(e=>e!==t&&e.hp>0).sort((a,b)=>Math.hypot(a.x-t.x,a.y-t.y)-Math.hypot(b.x-t.x,b.y-t.y))[0]||null}else s.dead=true}}for(const f of state.fx)f.t-=dt;state.enemies=state.enemies.filter(e=>{if(e.hp<=0){state.gold+=Math.max(1,Math.round(e.max/50));return false}return true});state.shots=state.shots.filter(s=>!s.dead);state.fx=state.fx.filter(f=>f.t>0);sync();if(state.wave===60&&state.bossSpawned&&!state.enemies.some(e=>e.boss)&&state.waveTime>5)return end(true);if(state.wave<60&&state.waveTime>state.waveDuration)chooseCards()}
function drawSprite(kind,row,col,x,y,size){let a=atlases[kind],i=a.i;if(!i.complete)return;let sw=i.naturalWidth/a.cols,sh=i.naturalHeight/a.rows;X.drawImage(i,col*sw,row*sh,sw,sh,x-size/2,y-size,size,size)}
function render(){X.clearRect(0,0,W,H);if(bg.complete)X.drawImage(bg,0,0,W,H);let ti=Math.max(0,Math.min(19,state.towerLevel-1));drawSprite('towers',Math.floor(ti/4),ti%4,W*.115,H*.70,Math.min(H*.38,280));let hpRatio=Math.max(0,state.hp/100),cc=hpRatio>.75?0:hpRatio>.5?1:hpRatio>.25?2:3;drawSprite('cupcake',0,cc,W*.205,H*.74,Math.min(H*.22,170));for(const e of [...state.enemies].sort((a,b)=>a.y-b.y)){drawSprite(e.set,e.row,e.attack?2:e.frame,e.x,e.y,e.size);X.fillStyle='#311';X.fillRect(e.x-e.size*.35,e.y-e.size*.88,e.size*.7,5);X.fillStyle=e.boss?'#b04cff':'#55c84a';X.fillRect(e.x-e.size*.35,e.y-e.size*.88,e.size*.7*Math.max(0,e.hp/e.max),5)}for(const s of state.shots){X.beginPath();X.arc(s.x,s.y,6,0,Math.PI*2);X.fillStyle=state.lightning?'#77d9ff':state.fire?'#ff7b1d':state.ice?'#9ee8ff':'#ffe584';X.shadowBlur=14;X.shadowColor=X.fillStyle;X.fill();X.shadowBlur=0}for(const f of state.fx){X.globalAlpha=Math.min(1,f.t*8);X.beginPath();X.arc(f.x,f.y,28*(1-f.t),0,Math.PI*2);X.fillStyle=f.type?'#a264ff':'#ffb12a';X.fill();X.globalAlpha=1}}
let last=performance.now();function loop(n){let dt=Math.min(.033,(n-last)/1000);last=n;if(state){update(dt);render()}requestAnimationFrame(loop)}requestAnimationFrame(loop);$('startBtn').onclick=()=>{$('splash').classList.add('hidden');$('game').classList.remove('hidden');reset()};