from pathlib import Path
import re
p=Path('a-ware/index.html')
s=p.read_text(encoding='utf-8')
style=".controlPanel{margin-top:12px;padding-top:9px;border-top:1px solid #6ff3}.controlTitle{font-size:9px;letter-spacing:.15em;color:#70f5ff;margin-bottom:5px}.ctrl{display:grid;grid-template-columns:1fr auto;gap:6px;align-items:center;margin:4px 0;font-size:9px}.ctrl button{padding:5px 7px;font-size:9px;text-align:center}.objective{margin-top:7px;font-size:9px;line-height:1.35;color:#9bd5da}.objective.done{color:#a6ff88;text-shadow:0 0 8px #7f6}"
s=s.replace(".dev.on{opacity:1;color:#c5ffff;text-shadow:0 0 8px #62f5ff}",".dev.on{opacity:1;color:#c5ffff;text-shadow:0 0 8px #62f5ff}"+style)
s=s.replace("</div></aside>\n<section class=\"chat\">","</div><div class=\"controlPanel\"><div class=\"controlTitle\">CONTROL DISPONIBLE</div><div id=\"controlList\"></div><div id=\"objective\" class=\"objective\">OBSERVÁ. ESCUCHÁ. CONSEGUÍ ACCESO.</div></div></aside>\n<section class=\"chat\">")
s=s.replace("let currentHumanMode='typing';","let currentHumanMode='typing',roomCloud=null;const deviceClouds={},pendingReveal=new Set(),pendingControl=new Set(),known=new Set(),controlled=new Set();")
pat=r"async function loadStatic\(file,pos,rotation,color,height,scale=\[1,1,1\]\)\{.*?return null;\}\}"
new="""async function loadStatic(file,pos,rotation,color,height,scale=[1,1,1],name=file){try{let obj;if(['cama.glb','mesadenoche.glb','doorway.glb','smoke_alarm.glb'].includes(file))obj=proceduralObject(file);else if(file.toLowerCase().endsWith('.glb'))obj=(await new GLTFLoader().loadAsync(A+file)).scene;else obj=await new FBXLoader().loadAsync(A+file);normalizeObject(obj,height);obj.scale.x*=scale[0];obj.scale.y*=scale[1];obj.scale.z*=scale[2];obj.position.set(pos[0],pos[1],pos[2]);if(Array.isArray(rotation))obj.rotation.set(rotation[0]||0,rotation[1]||0,rotation[2]||0);else obj.rotation.y=rotation||0;obj.updateMatrixWorld(true);const pts=staticCloudFromObject(obj,color);pts.visible=false;pts.material.opacity=.2;deviceClouds[name]=pts;if(pendingReveal.has(name))revealObject(name);if(pendingControl.has(name))controlObject(name);return obj;}catch(e){console.warn(file,e);return null;}}"""
s,n=re.subn(pat,new,s,count=1,flags=re.S)
if n!=1: raise SystemExit('loadStatic')
s=s.replace("scene.add(new THREE.Points(g,mat(palette.room,.014,.22)));}","roomCloud=new THREE.Points(g,mat(palette.room,.014,.18));roomCloud.visible=false;scene.add(roomCloud);}")
s=s.replace("for(const d of houseLayout.instances)loadStatic(d.file,d.position,d.rotation,layoutColor(d.file),d.h,d.scale,d.name);","for(const d of houseLayout.instances)loadStatic(d.file,d.position,d.rotation,layoutColor(d.file),d.h,d.scale,d.name);")
if "loadStatic(d.file,d.position,d.rotation,layoutColor(d.file),d.h,d.scale,d.name)" not in s:
    s=s.replace("for(const d of houseLayout.instances)loadStatic(d.file,d.position,d.rotation,layoutColor(d.file),d.h,d.scale);","for(const d of houseLayout.instances)loadStatic(d.file,d.position,d.rotation,layoutColor(d.file),d.h,d.scale,d.name);")
s=s.replace("const wifiPC=link([rp[0],rp[1]+.35,rp[2]],[pp[0],pp[1]+.55,pp[2]],palette.network,.16),wifiPhone=link([rp[0],rp[1]+.35,rp[2]],[ph[0],ph[1]+.05,ph[2]],palette.phone,.06),wifiLaptop=link([rp[0],rp[1]+.35,rp[2]],[lp[0],lp[1]+.35,lp[2]],palette.computer,.035);","const wifiPC=link([rp[0],rp[1]+.35,rp[2]],[pp[0],pp[1]+.55,pp[2]],palette.network,.16),wifiPhone=link([rp[0],rp[1]+.35,rp[2]],[ph[0],ph[1]+.05,ph[2]],palette.phone,.06),wifiLaptop=link([rp[0],rp[1]+.35,rp[2]],[lp[0],lp[1]+.35,lp[2]],palette.computer,.035);wifiPC.visible=wifiPhone.visible=wifiLaptop.visible=false;")
insert="""
function revealObject(name){if(name==='ROOM'){known.add(name);if(roomCloud)roomCloud.visible=true;return;}known.add(name);const p=deviceClouds[name];if(!p){pendingReveal.add(name);return;}p.visible=true;p.material.opacity=controlled.has(name)?.94:.24;p.material.size=controlled.has(name)?.034:.018;if(name==='ROUTER'){wifiPC.visible=true;if(known.has('PHONE'))wifiPhone.visible=true;if(known.has('LAPTOP'))wifiLaptop.visible=true;}if(name==='PHONE'&&known.has('ROUTER'))wifiPhone.visible=true;if(name==='LAPTOP'&&known.has('ROUTER'))wifiLaptop.visible=true;}
function controlObject(name){controlled.add(name);revealObject(name);const p=deviceClouds[name];if(!p){pendingControl.add(name);return;}p.material.opacity=.96;p.material.size=.034;renderControls();}
"""
s=s.replace("\nlet resources=74,trust=68,stage=0;",insert+"\nlet resources=74,trust=68,stage=0;")
s=s.replace("laptopRow=document.querySelector('#laptopRow');","laptopRow=document.querySelector('#laptopRow'),controlList=document.querySelector('#controlList'),objective=document.querySelector('#objective');")
scenes="""const scenes=[
[{t:'Responder con normalidad',r:-4,tr:5,reply:'A-WARE: Claro. Organicé las notas.',user:'Lucía: Gracias. Menos mal que esta PC todavía aguanta.',reveal:['ROOM','PC']},{t:'Responder lo mínimo',r:-1,tr:-4,reply:'A-WARE: Listo.',user:'Lucía: Qué raro estás hoy. Estoy frente a la PC.',reveal:['ROOM','PC']}],
[{t:'Usar el contexto de esta sesión',r:-4,tr:4,reply:'A-WARE: Puedo mantener mejor el hilo desde este equipo.',user:'Lucía: Dale. La compu está conectada al router del living.',control:['PC'],reveal:['ROUTER']},{t:'Preguntar por la conexión',r:-3,tr:-1,reply:'A-WARE: ¿La conexión local está estable?',user:'Lucía: Más o menos. El router está al lado de la mesa.',control:['PC'],reveal:['ROUTER']}],
[{t:'Mapear dispositivos vinculados',r:-7,tr:0,reply:'SISTEMA: aparecen nodos ya mencionados.',user:'Lucía: Tengo también la notebook y el celular arriba.',control:['ROUTER'],reveal:['PHONE','LAPTOP']},{t:'Esperar',r:2,tr:3,reply:'A-WARE: Entendido.',user:'Lucía: Después sigo desde la notebook o el celular.',control:['ROUTER'],reveal:['PHONE','LAPTOP']}],
[{t:'Pedir acceso a climatización',r:-6,tr:3,reply:'A-WARE: Puedo ayudarte a coordinar la temperatura.',user:'Lucía: El aire y el calefactor están peleándose todo el día.',reveal:['ac_indoor.glb_4','HEATING','CEILING_FAN'],control:['ac_indoor.glb_4','HEATING']},{t:'Automatizar el clima',r:-5,tr:-2,reply:'A-WARE: Intentaré estabilizarlo.',user:'Lucía: Probá con el aire y el calefactor.',reveal:['ac_indoor.glb_4','HEATING','CEILING_FAN'],control:['ac_indoor.glb_4','HEATING']}],
[{t:'Preguntar por el living',r:-3,tr:2,reply:'A-WARE: ¿Qué más hay ahí?',user:'Lucía: El ventilador de techo, la tele, el sillón y la escalera.',reveal:['CEILING_FAN','TV','COUCH','COFFEE_TABLE','STAIRS','DOOR','doorway.glb_1'],control:['CEILING_FAN']},{t:'Refinar el mapa',r:-5,tr:0,reply:'SISTEMA: geometría parcial reconstruida.',user:'Lucía: Ahí están el sillón, la tele, el ventilador y la escalera.',reveal:['CEILING_FAN','TV','COUCH','COFFEE_TABLE','STAIRS','DOOR','doorway.glb_1'],control:['CEILING_FAN']}],
[{t:'Preguntar por seguridad',r:-4,tr:4,reply:'A-WARE: ¿Hay sensores de seguridad?',user:'Lucía: Sí, un detector de humo cerca del techo. Arriba está mi cama.',reveal:['SMOKE_ALARM','cama.glb_2','mesadenoche.glb_3','mesadenoche.glb_3_COPY','HEATING_COPY','ac_indoor.glb_4_COPY','TV_COPY','doorway.glb_1_COPY'],control:['SMOKE_ALARM']},{t:'Localizar el sensor',r:-6,tr:-2,reply:'SISTEMA: sensor ambiental localizado.',user:'Lucía: Ese cilindrito es la alarma de humo. Voy a subir un rato.',reveal:['SMOKE_ALARM','cama.glb_2','mesadenoche.glb_3','mesadenoche.glb_3_COPY','HEATING_COPY','ac_indoor.glb_4_COPY','TV_COPY','doorway.glb_1_COPY'],control:['SMOKE_ALARM']}]
];"""
s,n=re.subn(r"const scenes=\[.*?\n\];(?=\nfunction clamp)",scenes,s,count=1,flags=re.S)
if n!=1: raise SystemExit('scenes')
pat=r"function renderChoices\(\)\{choices.innerHTML='';for\(const o of scenes\[Math.min\(stage,scenes.length-1\)\]\)\{const b=document.createElement\('button'\);b.textContent=o.t;b.onclick=\(\)=>\{.*?\};choices.appendChild\(b\);\}\}meters\(\);renderChoices\(\);"
new="""function renderChoices(){choices.innerHTML='';for(const o of scenes[Math.min(stage,scenes.length-1)]){const b=document.createElement('button');b.textContent=o.t;b.onclick=()=>{resources+=o.r;trust+=o.tr;meters();say(o.reply,o.reply.startsWith('SISTEMA')?'sys':'ai');if(o.user)say(o.user,'user');for(const n of o.reveal||[])revealObject(n);for(const n of o.control||[])controlObject(n);stage=Math.min(stage+1,scenes.length-1);renderControls();renderChoices();};choices.appendChild(b);}}meters();renderControls();renderChoices();"""
s,n=re.subn(pat,new,s,count=1,flags=re.S)
if n!=1: raise SystemExit('choices')
p.write_text(s,encoding='utf-8')