const $=id=>document.getElementById(id);
const I={};for(const [k,v] of Object.entries(DATA)){const im=new Image();im.src=v;I[k]=im}
const c=$('g'),x=c.getContext('2d');let W=innerWidth,H=innerHeight,D=Math.min(devicePixelRatio||1,2);
function resize(){W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
const S={wave:1,hp:100,gold:0,time:0,waveTime:0,spawnClock:0,enemies:[],shots:[],fx:[],speed:1,damage:16,delay:.72,lastShot:0,multi:1,crit:.05,pierce:0,chain:0,burn:0,slow:0,blast:0,cards:0,levels:{},paused:false,running:true,bossSpawned:false};
const UP={dmg:['⚔️','POTENCIA','+28% daño',s=>s.damage*=1.28],rate:['🏹','CADENCIA','15% más rápido',s=>s.delay=Math.max(.17,s.delay*.85)],multi:['➶','MULTIDISPARO','+1 flecha',s=>s.multi++],crit:['✦','CRÍTICO','+10% crítico',s=>s.crit=Math.min(.65,s.crit+.10)],pierce:['🪡','PERFORAR','+1 atravesado',s=>s.pierce++],chain:['⚡','RAYO','Salta a +1 enemigo',s=>s.chain++],burn:['🔥','FUEGO','Daño continuo',s=>s.burn+=2],slow:['❄️','HIELO','Ralentiza',s=>s.slow=Math.min(.6,s.slow+.09)],blast:['💥','EXPLOSIÓN','Daño de área',s=>s.blast+=8]};
function ui(){$('hp').textContent=Math.max(0,Math.ceil(S.hp));$('wave').textContent=S.wave;$('gold').textContent=S.gold;$('stats').innerHTML=`<span class=stat>DMG ${Math.round(S.damage)}</span><span class=stat>CAD ${S.delay.toFixed(2)}s</span><span class=stat>×${S.multi} flechas</span><span class=stat>⚡${S.chain}</span><span class=stat>🔥${S.burn}</span><span class=stat>❄️${Math.round(S.slow*100)}%</span>`;document.querySelectorAll('[data-s]').forEach(b=>b.classList.toggle('active',+b.dataset.s===S.speed))}
document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{S.speed=+b.dataset.s;ui()});
function enemyDef(){const boss=S.wave%10===0&&!S.bossSpawned;if(boss){S.bossSpawned=true;const bi=((S.wave/10-1)%3)+1;return{kind:'b'+bi,hp:420+S.wave*48,spd:22,size:112,boss:true}}const maxKind=Math.min(4,1+Math.floor(S.wave/4));const k=1+Math.floor(Math.random()*maxKind);return{kind:'e'+k,hp:(17+S.wave*5.4)*(k===1?.75:1),spd:30+Math.random()*10+(k===4?8:0),size:k===1?36:48,boss:false}}
function spawn(){const d=enemyDef(),lane=Math.random()*2-1,sy=H*(.48+lane*.015),my=H*(.57+lane*.11),ey=H*(.69+lane*.018);S.enemies.push({...d,x:W+70,y:sy,sy,my,ey,max:d.hp,frame:0,anim:0,attack:false,atk:0,slow:0,burn:0})}
function choose(){if(S.paused)return;S.paused=true;$('cards').classList.remove('hidden');$('cardrow').innerHTML='';for(const k of Object.keys(UP).sort(()=>Math.random()-.5).slice(0,3)){const u=UP[k],lv=(S.levels[k]||0)+1,d=document.createElement('div');d.className='card';d.innerHTML=`<div class=ico>${u[0]}</div><h3>${u[1]}</h3><b>NIVEL ${lv}</b><p>${u[2]}</p>`;d.onclick=()=>{S.levels[k]=lv;u[3](S);S.cards++;$('cards').classList.add('hidden');S.paused=false;S.wave++;S.waveTime=0;S.spawnClock=0;S.bossSpawned=false;ui()};$('cardrow').appendChild(d)}}
function fire(){let targets=S.enemies.filter(e=>e.hp>0).sort((a,b)=>a.x-b.x);if(!targets.length)return;for(let n=0;n<S.multi;n++)S.shots.push({x:W*.17,y:H*.52+(n-(S.multi-1)/2)*8,t:targets[Math.min(n,targets.length-1)],d:S.damage,p:S.pierce,dead:false})}
function damage(e,d){const q=d*(Math.random()<S.crit?2:1);e.hp-=q;e.burn=Math.max(e.burn,S.burn*3);e.slow=Math.max(e.slow,S.slow);S.fx.push({type:'hit',x:e.x,y:e.y,t:.18});if(S.blast)for(const o of S.enemies)if(o!==e&&Math.hypot(o.x-e.x,o.y-e.y)<80)o.hp-=S.blast;if(S.chain){let from=e;for(const o of S.enemies.filter(o=>o!==e&&o.hp>0).sort((a,b)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(b.x-e.x,b.y-e.y)).slice(0,S.chain)){o.hp-=q*.35;S.fx.push({type:'zap',a:from,b:o,t:.16});from=o}}}
function end(win){S.running=false;$('endtitle').textContent=win?'¡EL JARDÍN SOBREVIVIÓ!':'LA FLOR CAYÓ';$('endtext').textContent=win?'La torre llegó al final del bosque.':'Probá otra combinación de cartas.';$('end').classList.remove('hidden')}
function update(dt0){if(!S.running||S.paused)return;const dt=dt0*S.speed;S.time+=dt;S.waveTime+=dt;S.spawnClock+=dt;const interval=Math.max(.42,1.3-S.wave*.032);if(S.spawnClock>interval){S.spawnClock=0;spawn();if(S.wave>7&&Math.random()<.13)spawn()}if(S.time-S.lastShot>S.delay){S.lastShot=S.time;fire()}const goal=W*.255;for(const e of S.enemies){e.anim+=dt;if(e.anim>.13){e.anim=0;e.frame=(e.frame+1)%6}if(e.burn>0){e.hp-=S.burn*dt;e.burn-=dt}if(!e.attack){const target=goal+(e.boss?58:27),den=Math.max(1,W+70-target),p=Math.max(0,Math.min(1,(W+70-e.x)/den)),sm=t=>t*t*(3-2*t);e.y=p<.5?e.sy+(e.my-e.sy)*sm(p/.5):e.my+(e.ey-e.my)*sm((p-.5)/.5);e.x-=e.spd*(1-e.slow)*dt;if(e.x<=target){e.x=target;e.y=e.ey;e.attack=true;e.frame=0}}else{e.atk+=dt;S.hp-=dt*(e.boss?6:.55+S.wave*.022);e.y=e.ey+Math.sin(e.atk*10)*2;if(S.hp<=0){S.hp=0;ui();return end(false)}}}
for(const s of S.shots){if(s.dead)continue;let t=s.t;if(!t||t.hp<=0){t=S.enemies.filter(e=>e.hp>0).sort((a,b)=>Math.hypot(a.x-s.x,a.y-s.y)-Math.hypot(b.x-s.x,b.y-s.y))[0];s.t=t;if(!t){s.dead=true;continue}}const dx=t.x-s.x,dy=t.y-s.y,L=Math.hypot(dx,dy)||1;s.x+=dx/L*650*dt;s.y+=dy/L*650*dt;if(L<(t.boss?50:24)){damage(t,s.d);if(s.p>0)s.p--;else s.dead=true}}
for(const f of S.fx)f.t-=dt;S.enemies=S.enemies.filter(e=>{if(e.hp<=0){S.gold+=e.boss?30:1;return false}return true});S.shots=S.shots.filter(s=>!s.dead);S.fx=S.fx.filter(f=>f.t>0);ui();if(S.waveTime>32)choose();if(S.wave>30)end(true)}
function ready(img){return !!(img&&img.complete&&img.naturalWidth)}
function tile(img,sz=64){if(!ready(img))return false;for(let yy=0;yy<H;yy+=sz)for(let xx=0;xx<W;xx+=sz)x.drawImage(img,xx,yy,sz,sz);return true}
function sheet(img,frames,frame,cx,baseY,w,h,flip=false){if(!ready(img))return false;frames=Math.max(1,frames||1);const sw=img.naturalWidth/frames,sh=img.naturalHeight;x.save();if(flip){x.translate(cx*2,0);x.scale(-1,1)}x.drawImage(img,(frame%frames)*sw,0,sw,sh,cx-w/2,baseY-h,w,h);x.restore();return true}
function towerSprite(img,cx,baseY,h){if(!ready(img))return false;const frames=Math.max(1,Math.round(img.naturalWidth/70));const w=h*(70/130);return sheet(img,frames,Math.floor(S.time*5)%frames,cx,baseY,w,h,false)}
function fallbackTower(){x.fillStyle='#65472c';x.fillRect(W*.12,H*.48,72,H*.23);x.fillStyle='#91704b';x.fillRect(W*.105,H*.45,102,28);x.fillStyle='#352719';x.fillRect(W*.145,H*.55,22,H*.16)}
function render(){x.clearRect(0,0,W,H);if(!tile(I.grass2,64)){x.fillStyle='#4f7b35';x.fillRect(0,0,W,H)}if(ready(I.grass3)){x.globalAlpha=.18;tile(I.grass3,128);x.globalAlpha=1}
x.lineCap='round';x.strokeStyle='#71542f';x.lineWidth=Math.max(68,H*.115);x.beginPath();x.moveTo(W+40,H*.49);x.bezierCurveTo(W*.73,H*.48,W*.65,H*.70,W*.48,H*.60);x.bezierCurveTo(W*.37,H*.52,W*.33,H*.70,W*.255,H*.69);x.stroke();x.strokeStyle='#a77c43';x.lineWidth=Math.max(48,H*.078);x.stroke();
for(let i=0;i<8;i++){const xx=W*(.36+i*.085),yy=H*(.14+(i%3)*.055),im=i%2?I.tree2:I.tree1;if(ready(im))x.drawImage(im,xx,yy,86,108)}for(let i=0;i<12;i++){const xx=W*(.34+i*.055),yy=H*(.79+(i%3)*.018);if(ready(I.rock))x.drawImage(I.rock,xx,yy,36,30)}for(let i=0;i<8;i++){const xx=W*(.42+i*.07),yy=H*(.75+(i%2)*.045);if(ready(I.bush))x.drawImage(I.bush,xx,yy,50,42)}if(ready(I.camp))x.drawImage(I.camp,W*.79,H*.18,115,100);
if(ready(I.towerpad))x.drawImage(I.towerpad,W*.075,H*.62,120,80);const tl=Math.min(7,1+Math.floor(S.cards/5));if(!towerSprite(I['tower'+tl]||I.tower1,W*.155,H*.70,Math.min(280,H*.38)))fallbackTower();if(ready(I.flower))x.drawImage(I.flower,W*.225,H*.64,64,64);else{x.fillStyle='#f7df57';x.beginPath();x.arc(W*.255,H*.69,18,0,7);x.fill()}
const bossE=S.enemies.find(e=>e.boss&&e.hp>0);$('boss').classList.toggle('on',!!bossE);if(bossE)$('bossfill').style.width=(100*bossE.hp/bossE.max)+'%';
for(const e of [...S.enemies].sort((a,b)=>a.y-b.y)){const walk=I[e.kind+'walk']||I.e1walk,attack=I[e.kind+'attack']||I[e.kind+'special']||walk,img=e.attack?attack:walk,frames=6,w=e.size*(e.boss?1.8:1.5),h=e.size*(e.boss?1.45:1.22);if(!sheet(img,frames,e.frame,e.x,e.y,w,h,true)){x.fillStyle=e.boss?'#8b42a8':'#713d2b';x.fillRect(e.x-w/2,e.y-h,w,h)}x.fillStyle='#2a1717';x.fillRect(e.x-w*.35,e.y-h-7,w*.7,4);x.fillStyle=e.boss?'#d34fce':'#6ebc45';x.fillRect(e.x-w*.35,e.y-h-7,w*.7*Math.max(0,e.hp/e.max),4)}
for(const s of S.shots){x.fillStyle=S.burn?'#ff9c45':S.chain?'#80e8ff':'#ffe6a2';x.beginPath();x.arc(s.x,s.y,4,0,7);x.fill()}for(const f of S.fx){x.globalAlpha=Math.max(0,f.t/.18);if(f.type==='zap'){const a=f.a,b=f.b;x.strokeStyle='#9cecff';x.lineWidth=3;x.beginPath();x.moveTo(a.x,a.y-15);for(let i=1;i<6;i++){const q=i/6;x.lineTo(a.x+(b.x-a.x)*q+(Math.random()-.5)*10,a.y-15+(b.y-a.y)*q+(Math.random()-.5)*10)}x.lineTo(b.x,b.y-15);x.stroke()}else{x.strokeStyle='#fff2a7';x.lineWidth=2;x.beginPath();x.arc(f.x,f.y,18*(1-f.t/.18),0,7);x.stroke()}x.globalAlpha=1}}
let last=performance.now();function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);render();requestAnimationFrame(loop)}ui();requestAnimationFrame(loop);
