const sprites=['rabbit','carrot','plasma'];
const $=s=>document.querySelector(s);
const spriteSelect=$('#spriteSelect'), actionSelect=$('#actionSelect'), canvas=$('#canvas'), ctx=canvas.getContext('2d');
const fpsInput=$('#fps'), fpsValue=$('#fpsValue'), loopInput=$('#loop'), flipInput=$('#flip'), viewer=$('#viewer');
let meta=null, segments=[], frame=0, playing=true, last=0;
ctx.imageSmoothingEnabled=false;
function label(id){return {rabbit:'Conejo bazooka',carrot:'Zanahoria',plasma:'Bola de plasma'}[id]||id}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src;});}
async function loadSprite(id){meta=await fetch(`assets/sprites/${id}/metadata.json`,{cache:'no-store'}).then(r=>r.json());actionSelect.innerHTML='';Object.keys(meta.animations).forEach(a=>actionSelect.add(new Option(a,a)));spriteSelect.value=id;await loadAction();}
async function loadAction(){const a=meta.animations[actionSelect.value];fpsInput.value=a.fps;fpsValue.textContent=a.fps;loopInput.checked=a.loop;const defs=a.segments||[{file:a.sheet,count:a.count}];segments=await Promise.all(defs.map(async d=>({...d,image:await loadImage(`assets/sprites/${meta.id}/${d.file}?v=2`)})));frame=0;playing=true;$('#sizeInfo').textContent=`${meta.frameSize}×${meta.frameSize}px`;draw();}
function resolveFrame(globalFrame){let n=globalFrame;for(const seg of segments){if(n<seg.count)return {image:seg.image,local:n};n-=seg.count;}return {image:segments.at(-1).image,local:0};}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(!segments.length||!meta)return;const a=meta.animations[actionSelect.value],s=meta.frameSize,{image,local}=resolveFrame(frame);const scale=Math.max(1,Math.floor(Math.min(canvas.width/s,canvas.height/s)*.72));const w=s*scale,h=s*scale,x=(canvas.width-w)/2,y=(canvas.height-h)/2;ctx.save();ctx.imageSmoothingEnabled=false;if(flipInput.checked){ctx.translate(canvas.width,0);ctx.scale(-1,1);ctx.drawImage(image,local*s,0,s,s,canvas.width-x-w,y,w,h)}else ctx.drawImage(image,local*s,0,s,s,x,y,w,h);ctx.restore();$('#frameInfo').textContent=`${frame+1}/${a.count}`;}
function step(dir){const a=meta.animations[actionSelect.value];playing=false;frame=(frame+dir+a.count)%a.count;draw();}
function tick(t){if(playing&&segments.length&&meta){const a=meta.animations[actionSelect.value],interval=1000/Number(fpsInput.value);if(t-last>=interval){last=t;frame++;if(frame>=a.count){if(loopInput.checked)frame=0;else{frame=a.count-1;playing=false}}draw();}}requestAnimationFrame(tick);}
spriteSelect.innerHTML=sprites.map(s=>`<option value="${s}">${label(s)}</option>`).join('');spriteSelect.onchange=()=>loadSprite(spriteSelect.value);actionSelect.onchange=loadAction;fpsInput.oninput=()=>fpsValue.textContent=fpsInput.value;flipInput.onchange=draw;$('#play').onclick=()=>playing=true;$('#pause').onclick=()=>playing=false;$('#restart').onclick=()=>{frame=0;playing=true;draw()};$('#prev').onclick=()=>step(-1);$('#next').onclick=()=>step(1);$('#bgBtn').onclick=()=>viewer.classList.toggle('solid');$('#guidesBtn').onclick=()=>viewer.classList.toggle('hideGuides');loadSprite('rabbit');requestAnimationFrame(tick);
