import {joinRoom,selfId} from 'https://esm.sh/trystero@0.25.3';
import {APP_ID,MAX_PLAYERS,MIN_PLAYERS,THEMES,CONSEQUENCES,ROLES,TOPO_ROLE,AVATARS} from './game-data.js';
const css=document.createElement('link');css.rel='stylesheet';css.href='./game.css';document.head.appendChild(css);
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pick=a=>a[Math.floor(Math.random()*a.length)],shuffle=a=>[...a].sort(()=>Math.random()-.5),code=()=>Array.from({length:6},()=>pick('ABCDEFGHJKLMNPQRSTUVWXYZ23456789')).join('');
let room,acts={},isHost=false,hostId=null,myName='',myRole=null,myAvatar=null,roles={},joinN=0,protectedIds=new Set(),used={},adminUsed=new Set();
let game=fresh();function fresh(){return{phase:'lobby',theme:'escape',round:0,totalRounds:5,reputation:5,scenario:'',antagonist:THEMES.escape.antagonist,players:{},messages:[],voteCounts:{},votesCast:0,lastLeak:null,result:null}}
const me=()=>game.players[selfId],alive=()=>Object.entries(game.players).filter(([,p])=>p.alive!==false),roleDef=()=>myRole?.key==='topo'?TOPO_ROLE:ROLES.find(r=>r.key===myRole?.key);
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),2500)}
function sys(t){if(isHost)game.messages.push({id:crypto.randomUUID(),system:true,text:t,round:game.round,ts:Date.now()})}
function publicState(){const s=JSON.parse(JSON.stringify(game));delete s._votes;return s}
function state(){if(isHost)acts.state.send(publicState());renderAll()}
function avatarData(id){return AVATARS.find(a=>a.id===id)}
function avatarMarkup(p){const a=avatarData(p?.avatar);if(!a)return `<span>${esc((p?.name||'?')[0]?.toUpperCase())}</span>`;return `<img class="avatar-img" src="${a.file}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="avatar-fallback" style="display:none">${a.emoji}</span>`}
function renderAll(){if(game.phase!=='voting')used.voted=false;const theme=THEMES[game.theme]||THEMES.escape;document.querySelectorAll('#groupName,#sidebarGroupName,#infoGroupName').forEach(e=>e.textContent=theme.name);renderPlayers();renderMessages();renderBanner();renderActions();$('infoCount').textContent=`${Object.keys(game.players).length} participantes`;$('participantTitle').textContent=`${Object.keys(game.players).length} participantes`}
function renderPlayers(){const box=$('participants');box.innerHTML='';Object.entries(game.players).sort((a,b)=>a[1].joinIndex-b[1].joinIndex).forEach(([id,p])=>{const d=document.createElement('div');d.className='participant'+(p.alive===false?' eliminated':'');d.innerHTML=`<div class="participant-avatar">${avatarMarkup(p)}</div><div class="participant-copy"><strong>${esc(p.name)}${id===selfId?' (vos)':''}</strong><span>${p.disconnected?'desconectado':p.alive===false?'expulsado':p.avatar?'listo':'sin avatar'}</span></div>${id===hostId?'<span class="host-badge">ADMIN</span>':''}`;box.appendChild(d)})}
function renderMessages(){const box=$('messages');box.innerHTML='<div class="day-chip">HOY</div>';for(const m of game.messages){if(m.system){box.insertAdjacentHTML('beforeend',`<div class="system-chip">${esc(m.text)}</div>`);continue}const mine=m.authorId===selfId,p=game.players[m.authorId]||{name:m.author||'Anónimo'};box.insertAdjacentHTML('beforeend',`<div class="message-row ${mine?'mine':''}"><article class="bubble"><div class="sender-name">${mine?'Vos':esc(p.name)}</div><span class="${m.deleted?'deleted':''}">${m.deleted?'🚫 Este mensaje fue eliminado':esc(m.text)}</span><span class="bubble-meta">${new Date(m.ts).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}${mine?' <span class="ticks">✓✓</span>':''}</span></article></div>`)}box.scrollTop=box.scrollHeight}
function renderBanner(){const l={lobby:'Esperando jugadores',avatar:'Elegí tu avatar público',discussion:`Ronda ${game.round}/${game.totalRounds}`,leak:'El Topo está sacando una captura…',investigation:'Investigación',voting:'Encuesta de expulsión',between:'Fin de ronda',gameover:'Partida terminada'};$('gameBanner').textContent=`${l[game.phase]||game.phase} · Reputación ${'●'.repeat(game.reputation)}${'○'.repeat(5-game.reputation)}`+(game.scenario&&['discussion','leak','investigation','voting'].includes(game.phase)?` · ${game.scenario}`:'');$('gameBanner').classList.remove('hidden')}
function renderActions(){const t=$('actionTray');t.innerHTML='';t.classList.remove('hidden');if(!me()){t.innerHTML='<h4>Conectando…</h4>';return}if(me().alive===false){t.innerHTML='<h4>Fuiste expulsado. Seguís como espectador.</h4>';return}if(game.phase==='lobby'){t.innerHTML=`<h4>${isHost?'Compartí el código de sala.':'Esperando al administrador.'}</h4>`;if(isHost){const b=btn(`Iniciar partida (${Object.keys(game.players).length}/${MAX_PLAYERS})`,startGame,true);b.disabled=Object.keys(game.players).length<MIN_PLAYERS;t.appendChild(b)}return}if(game.phase==='avatar'){renderAvatars(t);if(isHost){const ready=Object.values(game.players).every(p=>p.avatar);const b=btn(ready?'Comenzar ronda':'Esperando avatares…',beginRound,true);b.disabled=!ready;t.appendChild(b)}return}if(game.phase==='discussion'){t.innerHTML='<h4>Debatan. Cualquier mensaje puede terminar en una captura.</h4>';renderAbility(t);if(isHost)t.appendChild(btn('Cerrar conversación y pasar a la filtración',()=>{game.phase='leak';sys('🔒 La conversación se cerró. El Topo está eligiendo qué filtrar.');state()},true));return}if(game.phase==='leak'){if(myRole?.key==='topo'){t.innerHTML='<h4>🐀 Elegí qué mensaje filtrar.</h4>';game.messages.filter(m=>!m.system&&!m.deleted&&m.round===game.round).slice(-25).forEach(m=>{const d=document.createElement('div');d.className='leak-choice';d.innerHTML=`<div><b>${esc(game.players[m.authorId]?.name||m.author)}</b>: ${esc(m.text)}</div><div class="small">La consecuencia será aleatoria.</div><button>📸 Filtrar esta captura</button>`;d.querySelector('button').onclick=()=>acts.leak.send({messageId:m.id});t.appendChild(d)})}else t.innerHTML='<h4>Algo está pasando fuera del grupo…</h4>';return}if(game.phase==='investigation'){t.innerHTML='<h4>Investiguen antes de votar.</h4>';renderAbility(t);if(isHost)t.appendChild(btn('Crear encuesta de expulsión',openVote,true));return}if(game.phase==='voting'){renderPoll(t);return}if(game.phase==='between'){t.innerHTML='<h4>El Topo sigue adentro.</h4>';if(isHost)t.appendChild(btn('Siguiente ronda',beginRound,true));return}if(game.phase==='gameover')t.innerHTML=`<h4>${esc(game.result)}</h4>`}
function btn(text,fn,primary=false){const b=document.createElement('button');b.className='action-btn'+(primary?' primary-action':'');b.textContent=text;b.onclick=fn;return b}
function renderAvatars(t){t.insertAdjacentHTML('beforeend','<h4>Elegí tu foto de perfil. Tu rol secreto NO se muestra.</h4><div class="avatar-grid"></div>');const g=t.querySelector('.avatar-grid'),taken=new Set(Object.values(game.players).map(p=>p.avatar).filter(Boolean));AVATARS.forEach(a=>{const b=document.createElement('button');b.className='avatar-option'+(myAvatar===a.id?' selected':'');b.disabled=taken.has(a.id)&&myAvatar!==a.id;b.innerHTML=`<span class="avatar-preview"><img src="${a.file}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span style="display:none">${a.emoji}</span></span><span>${esc(a.name)}</span>`;b.onclick=()=>{myAvatar=a.id;if(isHost)chooseAvatar(selfId,a.id);else acts.avatar.send({avatar:a.id});renderActions()};g.appendChild(b)})}
function chooseAvatar(id,a){if(game.phase!=='avatar'||!game.players[id])return;if(Object.entries(game.players).some(([x,p])=>x!==id&&p.avatar===a)){if(id===selfId)toast('Ese avatar ya fue elegido.');else acts.notice.send({text:'Ese avatar ya fue elegido.'},{target:id});return}game.players[id].avatar=a;if(id===selfId)myAvatar=a;state()}
function revealRole(r){myRole=r;const d=roleDef();document.querySelector('.eyebrow').textContent='TU ROL SECRETO';$('roleEmoji').textContent=d.emoji;$('roleName').textContent=d.name;$('roleDescription').textContent=d.desc;$('roleAlignment').textContent=r.key==='topo'?'TOPO':'LEAL';$('roleAlignment').classList.toggle('topo',r.key==='topo');$('roleModal').classList.remove('hidden')}
function connect(roomCode,host){isHost=host;hostId=host?selfId:null;game=fresh();roles={};used={};adminUsed=new Set();protectedIds=new Set();room=joinRoom({appId:APP_ID},`eltopo-${roomCode.toLowerCase()}`);['hello','state','chat','role','avatar','leak','ability','notice','vote','kick'].forEach(k=>acts[k]=room.makeAction(k));acts.hello.onMessage=(d,{peerId})=>{if(!isHost)return;if(game.phase!=='lobby')return acts.kick.send({reason:'La partida ya empezó.'},{target:peerId});if(Object.keys(game.players).length>=MAX_PLAYERS&&!game.players[peerId])return acts.kick.send({reason:'La sala ya está llena.'},{target:peerId});if(!game.players[peerId])game.players[peerId]={name:String(d.name||'Jugador').slice(0,20),avatar:null,alive:true,joinIndex:++joinN};acts.state.send(publicState(),{target:peerId});state()};acts.state.onMessage=(s,{peerId})=>{if(isHost)return;if(hostId&&peerId!==hostId)return;hostId=peerId;game=s;renderAll()};acts.chat.onMessage=(m,{peerId})=>{if(isHost){if(!game.players[peerId]?.alive)return;m={...m,authorId:peerId,author:game.players[peerId].name,text:String(m.text||'').slice(0,500)};game.messages.push(m);acts.chat.send(m);renderMessages()}else if(peerId===hostId&&!game.messages.some(x=>x.id===m.id)){game.messages.push(m);renderMessages()}};acts.role.onMessage=(r,{peerId})=>{if(peerId===hostId||!hostId){hostId=peerId;revealRole(r)}};acts.avatar.onMessage=(d,{peerId})=>isHost&&chooseAvatar(peerId,d.avatar);acts.leak.onMessage=(d,{peerId})=>isHost&&handleLeak(peerId,d.messageId);acts.ability.onMessage=(d,{peerId})=>isHost&&handleAbility(peerId,d);acts.notice.onMessage=(d,{peerId})=>{if(peerId===hostId)toast(d.text)};acts.vote.onMessage=(d,{peerId})=>isHost&&vote(peerId,d.target);acts.kick.onMessage=(d,{peerId})=>{if(!hostId||peerId===hostId){alert(d.reason);leave()}};room.onPeerLeave=id=>{if(isHost&&game.players[id]){game.players[id].disconnected=true;if(game.phase==='lobby')delete game.players[id];state()}else if(id===hostId)toast('El administrador se desconectó.')};$('roomCodeDisplay').textContent=roomCode;$('meAvatar').textContent=myName[0].toUpperCase();if(isHost){game.players[selfId]={name:myName,avatar:null,alive:true,joinIndex:++joinN};hostId=selfId;$('hostSettings').classList.remove('hidden');renderAll()}else{$('hostSettings').classList.add('hidden');acts.hello.send({name:myName});setTimeout(()=>{if(!hostId)toast('Todavía no encontré la sala. Revisá el código.')},9000)}}
function startGame(){if(Object.keys(game.players).length<MIN_PLAYERS)return toast(`Se necesitan al menos ${MIN_PLAYERS} jugadores.`);game.totalRounds=Number($('roundsSelect').value||5);game.theme=$('themeSelect').value;game.antagonist=THEMES[game.theme].antagonist;const ids=shuffle(Object.keys(game.players));roles[ids[0]]=TOPO_ROLE;ids.slice(1).forEach((id,i)=>roles[id]=ROLES[i%ROLES.length]);Object.entries(roles).forEach(([id,r])=>id===selfId?revealRole({key:r.key}):acts.role.send({key:r.key},{target:id}));game.phase='avatar';sys('🔐 Los roles secretos fueron repartidos. Ahora elijan un avatar público.');state()}
function beginRound(){if(game.round>=game.totalRounds)return end(false);game.round++;game.phase='discussion';game.scenario=pick(THEMES[game.theme].situations);game.voteCounts={};game.votesCast=0;sys(`📌 SITUACIÓN ${game.round}: ${game.scenario}`);sys('Hablen libremente. Alguien puede sacar una captura.');state()}
function sendChat(){const i=$('messageInput'),text=i.value.trim();if(!text)return;if(!me()?.alive)return toast('Estás expulsado.');if(!['discussion','lobby'].includes(game.phase))return toast('El chat está cerrado.');const m={id:crypto.randomUUID(),authorId:selfId,author:myName,text:text.slice(0,500),ts:Date.now(),round:game.round,deleted:false};i.value='';if(isHost){game.messages.push(m);acts.chat.send(m);renderMessages()}else acts.chat.send(m)}
function handleLeak(id,messageId){if(game.phase!=='leak'||roles[id]?.key!=='topo')return;const m=game.messages.find(x=>x.id===messageId);if(!m||m.deleted||protectedIds.has(messageId))return acts.notice.send({text:'Ese mensaje no puede filtrarse.'},{target:id});game.reputation--;sys(`📸 SE FILTRÓ UNA CAPTURA: “${m.text}”`);sys(`📤 Destinatario: ${game.antagonist}. ${pick(CONSEQUENCES)}`);if(game.reputation<=0)return end(false);game.phase='investigation';state()}
function renderAbility(t){const k=myRole?.key;if(!k||used[k])return;let label='';if(game.phase==='investigation'&&k==='investigador')label='🕵️ Investigar sospechosos';if(game.phase==='investigation'&&k==='tecnico')label='💻 Pedir pista técnica';if(game.phase==='discussion'&&k==='seguridad')label='🛡️ Proteger un mensaje';if(game.phase==='discussion'&&k==='editor')label='🧹 Eliminar uno de mis mensajes';if(game.phase==='discussion'&&k==='confidente')label='🤫 Enviar mensaje anónimo';if(label)t.appendChild(btn(label,()=>useAbility(k)))}
function useAbility(k){if(['seguridad','editor'].includes(k)){const mineOnly=k==='editor',arr=game.messages.filter(m=>!m.system&&!m.deleted&&m.round===game.round&&(!mineOnly||m.authorId===selfId)).slice(-10);if(!arr.length)return toast('No hay mensajes válidos.');const n=Number(prompt(arr.map((m,i)=>`${i+1}. ${game.players[m.authorId]?.name||m.author}: ${m.text.slice(0,55)}`).join('\n'))),m=arr[n-1];if(!m)return;acts.ability.send({type:k==='seguridad'?'protect':'delete',messageId:m.id})}else if(k==='confidente'){const text=prompt('Mensaje anónimo:');if(text?.trim())acts.ability.send({type:'anonymous',text:text.trim().slice(0,300)})}else acts.ability.send({type:k});used[k]=true;renderActions()}
function handleAbility(id,d){const k=roles[id]?.key;if(d.type==='investigador'&&k==='investigador'){const topo=Object.keys(roles).find(x=>roles[x].key==='topo'),sus=shuffle([topo,...shuffle(alive().map(([x])=>x).filter(x=>x!==topo)).slice(0,2)]).map(x=>game.players[x]?.name).filter(Boolean);acts.notice.send({text:`Pista: el Topo está entre ${sus.join(', ')}.`},{target:id})}if(d.type==='tecnico'&&k==='tecnico'){const topo=Object.keys(roles).find(x=>roles[x].key==='topo'),half=Math.ceil(Object.keys(game.players).length/2);acts.notice.send({text:`Pista técnica: el Topo llegó en la ${game.players[topo].joinIndex<=half?'primera':'segunda'} mitad del orden de conexión.`},{target:id})}if(d.type==='protect'&&k==='seguridad'){protectedIds.add(d.messageId);acts.notice.send({text:'Mensaje protegido.'},{target:id})}if(d.type==='delete'&&k==='editor'){const m=game.messages.find(x=>x.id===d.messageId&&x.authorId===id);if(m){m.deleted=true;state()}}if(d.type==='anonymous'&&k==='confidente'){const m={id:crypto.randomUUID(),authorId:'anon',author:'Anónimo',text:d.text,ts:Date.now(),round:game.round,deleted:false};game.messages.push(m);acts.chat.send(m);renderMessages()}}
function openVote(){game.phase='voting';game.voteCounts={};game.votesCast=0;game._votes={};sys('📊 Los administradores abrieron una encuesta: ¿a quién echamos?');state()}
function renderPoll(t){t.innerHTML='<div class="poll-card"><h3>¿Quién es el Topo?</h3><p>Elegí a una persona.</p><div class="poll-options"></div><div class="poll-footer"></div></div>';const o=t.querySelector('.poll-options');alive().forEach(([id,p])=>{if(id===selfId)return;const r=document.createElement('div');r.className='poll-option';r.innerHTML=`<span class="poll-radio"></span><span class="poll-name">${esc(p.name)}</span><span class="poll-count">${game.voteCounts[id]||0}</span>`;r.onclick=()=>{if(used.voted)return toast('Ya votaste.');used.voted=true;isHost?vote(selfId,id):acts.vote.send({target:id});renderActions()};o.appendChild(r)});t.querySelector('.poll-footer').textContent=`${game.votesCast||0} de ${alive().length} votos`;if(isHost)t.appendChild(btn('Cerrar encuesta y expulsar',resolveVote,true))}
function vote(id,target){if(game.phase!=='voting'||!game.players[id]?.alive||!game.players[target]?.alive||game._votes?.[id])return;game._votes[id]=target;let w=1;if(roles[id]?.key==='administrador'&&!adminUsed.has(id)){w=2;adminUsed.add(id)}game.voteCounts[target]=(game.voteCounts[target]||0)+w;game.votesCast=Object.keys(game._votes).length;state()}
function resolveVote(){const e=Object.entries(game.voteCounts).sort((a,b)=>b[1]-a[1]);if(!e.length||e[1]&&e[0][1]===e[1][1]){sys(!e.length?'La encuesta terminó sin votos.':'🤝 Hubo empate. Nadie fue expulsado.');return between()}const id=e[0][0];game.players[id].alive=false;sys(`🚪 ${game.players[id].name} fue expulsado. Su rol no se revela.`);if(roles[id]?.key==='topo')return end(true);game.reputation--;if(game.reputation<=0||game.round>=game.totalRounds)return end(false);between()}
function between(){game.phase='between';game._votes={};state()}
function end(leals){game.phase='gameover';const topo=Object.keys(roles).find(id=>roles[id].key==='topo'),name=game.players[topo]?.name||'El Topo';game.result=leals?`✅ Descubrieron al Topo: ${name}. ¡Ganan los leales!`:`🐀 ${name} era el Topo y sobrevivió. ¡Gana el Topo!`;sys(game.result);state()}
function leave(){try{room?.leave()}catch{}room=null;$('messenger').classList.remove('active');$('landing').classList.add('active')}
$('createRoomBtn').onclick=()=>{myName=$('playerName').value.trim();if(!myName)return $('landingError').textContent='Poné tu nombre.';$('landingError').textContent='';$('landing').classList.remove('active');$('messenger').classList.add('active');connect(code(),true)};$('joinRoomBtn').onclick=()=>{myName=$('playerName').value.trim();const c=$('roomCodeInput').value.trim().toUpperCase();if(!myName||!c)return $('landingError').textContent='Poné tu nombre y código.';$('landingError').textContent='';$('landing').classList.remove('active');$('messenger').classList.add('active');connect(c,false)};$('sendBtn').onclick=sendChat;$('messageInput').onkeydown=e=>e.key==='Enter'&&sendChat();$('groupInfoBtn').onclick=()=>$('infoPanel').classList.add('open');$('closeInfoBtn').onclick=()=>$('infoPanel').classList.remove('open');$('closeRoleBtn').onclick=()=>{$('roleModal').classList.add('hidden');renderActions()};$('copyCodeBtn').onclick=async()=>{try{await navigator.clipboard.writeText($('roomCodeDisplay').textContent);toast('Código copiado.')}catch{}};$('leaveRoomBtn').onclick=leave;$('themeSelect').onchange=e=>{if(isHost&&game.phase==='lobby'){game.theme=e.target.value;game.antagonist=THEMES[game.theme].antagonist;state()}};$('roundsSelect').onchange=e=>{if(isHost&&game.phase==='lobby'){game.totalRounds=Number(e.target.value);state()}};$('startGameBtn').onclick=startGame;
renderAll();
